export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";

export const SOCKET_SET = "SOCKET_SET";

export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const MESSAGE_SENT = "MESSAGE_SENT";
export const STREAM_RECEIVED = "STREAM_RECEIVED";
export const END_STREAM = "END_STREAM";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const LOAD_MESSAGES = "LOAD_MESSAGES";

export const SET_ACTIVE_CONTEXT = "SET_ACTIVE_CONTEXT";
export const SET_CONTEXTS = "SET_CONTEXTS";
export const LOAD_CONTEXT = "LOAD_CONTEXT";
export const ADD_CONTEXT = "ADD_CONTEXT";
export const UPDATE_CONTEXT = "UPDATE_CONTEXT";
export const DELETE_CONTEXT = "DELETE_CONTEXT";
export const ADD_CONTEXT_AND_SET = "ADD_CONTEXT_AND_SET";
export const REMOVE_FILE_FROM_CONTEXT = "REMOVE_FILE_FROM_CONTEXT";

export const SHOW_UPLOAD_MODAL = "SHOW_UPLOAD_MODAL";
export const SHOW_PROMPT_MODAL = "SHOW_PROMPT_MODAL";

export const SET_SYSTEM_PROMPT = "SET_SYSTEM_PROMPT";
export const SET_SYSTEM_PROMPTS = "SET_SYSTEM_PROMPTS";
